version: "3"

tasks:
  default:
    cmds:
      - task: generate
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      # Генерация Go файлов
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
      # Генерация JavaScript файлов для grpc-web
      - protoc -I proto proto/sso/*.proto --js_out=import_style=commonjs:./gen/js --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./gen/js