version: "3"  

tasks:  
  default:
    cmds:  
      - task: generate  
  generate:
    aliases:
      - gen  
    desc: "Generate code from proto files"  
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
      - grpc_tools_node_protoc -I proto --js_out=import_style=commonjs:./gen/js --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./gen/js proto/sso/*.proto